markdown:	kramdown
pygments:	true

permalink:	/:title

title:		Subjective-C
tagline:	'a study of innovative iOS interfaces'
description:	'<strong>Subjective-C</strong> is a study of innovative iOS interfaces.'
url:		http://subjc.com
icon:   /assets/images/icon.png

author:
  name: Sam Page
  url: http://twitter.com/sampage/

social:
  - icon:	twitter
    url:	https://twitter.com/subjc
    desc:	Follow Subjective-C on twitter

  - icon:	github
    url:	https://github.com/subjc
    desc:	Fork me on github

  - icon: mail
    url: mailto:sam@subjc.com
    desc: sam@subjc.com 


  - icon:	feed
    url:	http://subjc.com/atom.xml
    desc:	Subscribe to the feed

attribution:
  jekyll: 
    desc: Jekyll
    url: http://jekyllrb.com/

  thinny: 
    desc: Thinny
    url: http://camporez.com/blog/thinny-2/

license:
  type: Creative Commons BY-NC
  url: http://creativecommons.org/licenses/by-nc/3.0/
